name: "BASM Library by Triploit"
version: "0.0.1"
description: "A tiny standard library for basm programming language"
information: ""

authors:
  - survari

products:
  - "./lib/": "/usr/include/basm/"

dependencies:
  - triploit:basm@github.com

gituser: triploit
server: github.com
reponame: basm-lib
